djangoVaccination/djangoVaccination/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('vaccin/', include("vaccin.urls")),
    path('centre/', include("centre.urls")),
    path('patient/', include("patient.urls")),
    path('stock/', include("stock.urls")),
    path('rdv/', include("rdv.urls")),
    path('search/', include("search.urls")),
]

djangoVaccination/patient/urls.py
from django.urls import path
from patient import views

app_name = 'patient'
urlpatterns = [
    path(r'', views.patientReadAll, name='patientReadAll'),
    path(r'?action=patientReadId&target=patientReadOne', views.patientReadId, name='patientReadId'),
    path(r'?action=patientReadOne', views.patientReadOne, name='patientReadOne'),
    path(r'?action=patientCreate', views.patientCreate, name='patientCreate'),
    path(r'?action=patientCreated', views.patientCreated, name='patientCreated'),
    path(r'?action=patientReadDistinct', views.patientReadDistinct, name='patientReadDistinct'),
    path(r'?action=quantityByAdresse', views.quantityByAdresse, name='quantityByAdresse'),    
    path(r'?action=patientReadId&target=patientDeleted', views.patientReadId, name='patientDelete'),
    path(r'?action=patientDeleted', views.patientDeleted, name='patientDeleted'),
]

djangoVaccination/rdv/urls.py
from django.urls import path
from rdv import views

app_name = 'rdv'
urlpatterns = [
    path(r'?action=rdvReadPatient&target=rdvPropos', views.rdvReadPatient, name='rdvReadPatient'),
    path(r'?action=rdvPropos', views.rdvPropos, name='rdvPropos'),
    path(r'?action=setRdv', views.setRdv, name='setRdv'),
    path(r'?action=rdvReadAll', views.rdvReadAll, name='rdvReadAll'),
]

djangoVaccination/patient/models.py
from django.db import connection
from django.db import models

# Create your models here.
class ModelPatient(models.Model):
    nom = models.CharField(max_length=40)
    prenom = models.CharField(max_length=40)
    adresse = models.CharField(max_length=80)

    @staticmethod
    def getAll():
        sql_command = "SELECT * FROM patient"
        patient_rows = ModelPatient.objects.raw(sql_command)
        return patient_rows

    @staticmethod
    def getAllId():
        try:
            sql_command = "SELECT * FROM patient ORDER BY id"
            patient_rows = ModelPatient.objects.raw(sql_command)
            return patient_rows
        except Exception:
            return None

    @staticmethod
    def getOne(patient_id):
        try:
            sql_command = "SELECT * FROM patient WHERE id=%s"
            patient_rows = ModelPatient.objects.raw(sql_command, [patient_id])
            return patient_rows
        except Exception:
            return None

    @staticmethod
    def insert(patient_nom, patient_prenom, patient_adresse):
        sql_idMax = "SELECT MAX(id) FROM patient"
        with connection.cursor() as cursor:
            cursor.execute(sql_idMax)
            idMax = int(cursor.fetchone()[0]) + 1

        with connection.cursor() as cursor:
            sql_command = "INSERT INTO patient VALUE (%s, %s, %s, %s);"
            cursor.execute(sql_command, [idMax, patient_nom, patient_prenom, patient_adresse])

        # vaccin_inserted = ModelVaccin.objects.raw(sql_command, [idMax, label, doses])
        return idMax

    @staticmethod
    def patientReadDistinct():
        try:
            sql_commande = "SELECT DISTINCT adresse FROM patient"
            with connection.cursor() as cursor:
                cursor.execute(sql_commande)
                patient_rows = cursor.fetchall()
                return patient_rows
        except Exception:
            return None

    @staticmethod
    def getPatientQuantityByAddress():
        try:
            distinct_adresses = ModelPatient.patientReadDistinct()
            quantity_by_adresse = []
            result = []

            for adresse in distinct_adresses:
                sql_command = "SELECT COUNT(adresse) AS quantite FROM patient WHERE adresse=%s"
                with connection.cursor() as cursor:
                    cursor.execute(sql_command, [adresse])
                    quantity = cursor.fetchall()[0][0]
                    quantity_by_adresse.append(quantity)
                    result.append({'adresse': adresse, 'quantity': quantity})

            return {"adresse_info": result, "quantity": quantity_by_adresse}
        except Exception:
            return None

    @staticmethod
    def deleteId(patient_id):
        try:
            # Supprimer un patient dans la table rendezvous (s'il y existe)
            sql_command = "DELETE FROM rendezvous WHERE patient_id = %s"
            with connection.cursor() as cursor:
                cursor.execute(sql_command, [patient_id])
            
            # Supprimer un patient dans la table patient 
            sql_command = "DELETE FROM patient WHERE id = %s"
            with connection.cursor() as cursor:
                cursor.execute(sql_command, [patient_id])
            
            return patient_id;
        except Exception:
            print("ERROR")
            return None;
        

    class Meta:
        db_table = "patient"

djangoVaccination/patient/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import ModelPatient
import re

# Create your views here.
def strip_tags(value):
    """Return the given HTML with all tags stripped."""
    # Note: in typical case this loop executes _strip_once once. Loop condition
    # is redundant, but helps to reduce number of executions of _strip_once.
    value = str(value)
    while '<' in value and '>' in value:
        new_value = _strip_once(value)
        if value.count('<') == new_value.count('<'):
            # _strip_once wasn't able to detect more tags.
            break
        value = new_value
    return value


# Show list of patients
def patientReadAll(request):
    patient_info = ModelPatient.getAll()
    patient_dict = {'patient_info': patient_info}

    return render(request, "patient/viewAll.html", context=patient_dict)


def patientReadId(request):
    if request.method == 'GET':
        path_info = request.META['PATH_INFO']
        query_str = re.search(r'target\=[a-zA-Z0-9]*', path_info).group()
        target_value = re.split(r'target\=|\&', query_str)[1]
        target = f'patient:{target_value}'

        patient_info = ModelPatient.getAll()
        patient_dict = {'patient_info': patient_info, 'target': target}

        return render(request, 'patient/viewId.html', context=patient_dict)
    patient_dict = {}
    return render(request, "patient/viewId.html", context=patient_dict)


def patientReadOne(request):
    if request.method == 'GET':
        patient_id = re.split(r":", request.GET['patientInfo'])[0].strip()
        patient_info = ModelPatient.getOne(patient_id)
        patient_dict = {'patient_info': patient_info}
        return render(request, "patient/viewAll.html", context=patient_dict)


# Page of patient's creation
def patientCreate(request):
    return render(request, "patient/viewInsert.html", context={})

# Page after creating a new patient
@csrf_exempt
def patientCreated(request):
    if request.method == 'POST':
        nom = request.POST['nom'].strip()
        prenom = request.POST['prenom'].strip()
        adresse = request.POST['adresse'].strip()

        condition1 = (not nom) or (not prenom) or (not adresse)
        condition2 = (len(nom) > 0) and (len(prenom) > 0) and (len(adresse) > 0)

        if (condition1):
            info_dict = {'result': False}
        elif (condition2):
            try:
                # Add new vaccine to database (table 'vaccin')
                id = ModelPatient.insert(strip_tags(nom), strip_tags(prenom), strip_tags(adresse))
                patient_info = ModelPatient.getAll()

                info_dict = {'result': True, 'id': id, 'nom': nom,
                            'prenom': prenom, 'adresse': adresse, 'patient_info': patient_info}
            except Exception:
                info_dict = {'result': False}

        return render(request, 'patient/viewInserted.html', context=info_dict)


def patientReadDistinct(request):
    adresse_info = ModelPatient.patientReadDistinct()
    return render(request, "patient/viewDistinct.html", context={'adresse_info': adresse_info, 'quantity': None})

def quantityByAdresse(request):
    info_dict = ModelPatient.getPatientQuantityByAddress()
    return render(request, "patient/viewDistinct.html", context=info_dict)

# Delete a patient
def patientDeleted(request):
    if request.method == 'GET':
        patient_id = re.split(r":", request.GET['patientInfo'])[0].strip()
        patient_nom = re.split(r":", request.GET['patientInfo'])[1].strip()
        patient_adresse = re.split(r":", request.GET['patientInfo'])[2].strip()
        # Delete a patient in the tables 'patient' and 'rendezvous'
        ModelPatient.deleteId(patient_id)

        patient_info = ModelPatient.getAll()
        patient_dict = {'patient_info': patient_info, 'id': patient_id, 'nom': patient_nom, 'adresse': patient_adresse}

        return render(request, "patient/viewDeleted.html", context=patient_dict)

djangoVaccination/templates/patient/viewAll.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">
            Liste des patients en attente...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    <form class="navbar-form navbar-right" role="search" method="get" action="router2.php" style="margin-bottom: 14px">
        <input type="hidden" name="action" value="searchPatient">
        <div class="form-group">
            <input name="searching" type="text" class="form-control" size='44' placeholder="Rechercher par nom du patient...">
        </div>
        <button type="submit" class="btn btn-danger">Rechercher</button>
    </form>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #AA6C39">
                <th scope="col">id</th>
                <th scope="col">nom</th>
                <th scope="col">prenom</th>
                <th scope="col">adresse</th>
            </tr>
        </thead>

        <tbody>
            {% for patient in patient_info %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.nom }}</td>
                <td>{{ patient.prenom }}</td>
                <td>{{ patient.adresse }}</td>
            </tr> 
            {% endfor %}         
        </tbody>
    </table>
    {% endblock %}

djangoVaccination/templates/patient/viewDeleted.html
{% extends 'fragment/framePage.html' %}
    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    <div style="margin-bottom: 20px">
        <h3>Le patient {{ id }} : {{ nom }} : {{ adresse }} a bien été supprimé.
            <br> Voici la nouvelle liste des patients : <br>
        </h3>
    </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #AA6C39">
                <th scope="col">id</th>
                <th scope="col">nom</th>
                <th scope="col">nom</th>
                <th scope="col">adresse</th>
            </tr>
        </thead>
        
        <tbody>
        {% comment %} La liste des patients est dans une variable $results {% endcomment %}
        {% for patient in patient_info %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.nom }}</td>
                <td>{{ patient.prenom }}</td>
                <td>{{ patient.adresse }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endblock %}

djangoVaccination/templates/patient/viewDistinct.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">
            Liste des adresses des patients ...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    <h3>Evolution de COVID-19: </h3>
    
    <table class = "table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #d4edda;">
                <th scope = "col">Liste sans doublon des addresses de patients</th>
                {% if quantity != None %}
                <th scope = "col">Nombre de patients</th>
                {% endif %}
            </tr>
        </thead>
        
        <tbody>
            {% if quantity != None %}
                {% for info in adresse_info %} 
                    <tr>
                        <td>{{ info.adresse.0 }}</td>
                        <td>{{ info.quantity }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                {% for adresse in adresse_info %}
                    <tr>
                        <td>{{ adresse.0 }}</td>
                    </tr> 
                {% endfor %}  
            {% endif %}
        </tbody>
    </table>
    {% endblock %}

djangoVaccination/templates/patient/viewId.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">Liste des patients en attente ...</div>
    </div>
    {% endblock %}

    {% block body_block %}
        {% block jumbotron_block %}
            {% include "fragment/frameJumbotron.html" %}
        {% endblock %}

    <form role="form" method="GET" action="{% url target %}" style="margin-bottom: 8px;">
        <div class="form-group">
            {% comment %} <input type="hidden" name='action' value={{target}}> {% endcomment %}
            <label for="patientInfo">Choisir un patient : </label> 
            <select class="form-control" id='patientInfo' name='patientInfo' style="width: 140px">
                {% for patient in patient_info %}
                    <option>{{ patient.id}} : {{ patient.nom }} {{ patient.prenom }} : {{ patient.adresse }}</option>
                {% endfor %}
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Submit form</button>
    </form>
    {% endblock %}

djangoVaccination/templates/patient/viewInsert.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">
            Vous voulez ajouter un nouveau patient ? <br>
            Allez-y !
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    {% csrf_token %}
    <form role="form" method="POST" action="{% url 'patient:patientCreated' %}" style="margin-bottom: 8px;">
        <div class="form-group">
            <input type="hidden" name='action' value='patientCreated'>
            <label for="id">nom : </label><input type="text" name='nom' size='45' value='Lennon'>
            <label for="id">prenom : </label><input type="text" name='prenom' size='45' value='John'>
            <label for="id">adresse : </label><input type="text" name='adresse' size='35' value='Paris'>
        </div>
        <button class="btn btn-primary" type="submit">Go</button>
    </form>
    {% endblock %}

djangoVaccination/templates/patient/viewInserted.html
{% extends "fragment/framePage.html" %} 
{% block body_block %} 
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    {% if result %}
    <h3>Le nouveau patient a été ajouté</h3>
    <ul>
        <li>id = {{ id }}</li>
        <li>nom = {{ nom }}</li>
        <li>prenom = {{ prenom }}</li>
        <li>adresse = {{ adresse }}</li>
    </ul>

    <h3>Voici la nouvelle liste des patients:</h3>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #aa6c39">
                <th scope="col">id</th>
                <th scope="col">nom</th>
                <th scope="col">prénom</th>
                <th scope="col">adresse</th>
            </tr>
        </thead>
        <tbody>
            {% for patient in patient_info %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.nom }}</td>
                <td>{{ patient.prenom }}</td>
                <td>{{ patient.adresse }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
        <h3>Problème d'insertion du patient.</h3>
        <h3 style="color: red" ;>
        Veuillez vérifier toutes les infos du patient dans le formulaire ont été bien
        renseignées.
        </h3>
    {% endif %}

    <button class="btn btn-primary" style="margin-bottom: 7px" onclick="history.go(-1)" style="margin-bottom: 8px">
    Page précédente
    </button>
{% endblock %}