djangoVaccination/djangoVaccination/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('vaccin/', include("vaccin.urls")),
    path('centre/', include("centre.urls")),
    path('patient/', include("patient.urls")),
    path('stock/', include("stock.urls")),
    path('rdv/', include("rdv.urls")),
    path('search/', include("search.urls")),
]

djangoVaccination/rdv/urls.py
from django.urls import path
from rdv import views

app_name = 'rdv'
urlpatterns = [
    path(r'?action=rdvReadPatient&target=rdvPropos', views.rdvReadPatient, name='rdvReadPatient'),
    path(r'?action=rdvPropos', views.rdvPropos, name='rdvPropos'),
    path(r'?action=setRdv', views.setRdv, name='setRdv'),
    path(r'?action=rdvReadAll', views.rdvReadAll, name='rdvReadAll'),
]

djangoVaccination/rdv/models.py
from django.db import connection
from django.db import models

# Create your models here.


class ModelRdv(models.Model):
    # Prendre la liste des rendez-vous
    def getAll():
        try:
            sql_command = "SELECT patient.nom, patient.prenom, centre.label as centre_label, centre.adresse as centre_adresse, rendezvous.injection as injection, vaccin.label as vaccin_label FROM patient JOIN rendezvous ON patient.id = rendezvous.patient_id JOIN centre ON centre.id = rendezvous.centre_id JOIN vaccin ON vaccin.id = rendezvous.vaccin_id ORDER BY rendezvous.patient_id"
            with connection.cursor() as cursor:
                cursor.execute(sql_command)
                results = cursor.fetchall()

                return results
        except Exception:
            print("ERROR")
            return 0


    # Prendre l'injection du patient
    def getInjection(patient_id):
        try:
            sql_command = "SELECT rendezvous.injection as injection FROM rendezvous WHERE rendezvous.patient_id=%s"
            with connection.cursor() as cursor:
                cursor.execute(sql_command, [patient_id])
                results = cursor.fetchall()
                results = results[len(results) - 1][0]
                return results
        except Exception:
            print("ERROR")
            return 0


    # Prendre les infos de patients
    def getPatient():
        try:
            sql_command = "SELECT id, nom, prenom, adresse FROM patient"
            with connection.cursor() as cursor:
                cursor.execute(sql_command)
                results = cursor.fetchall()

                return results
        except Exception:
            print("ERROR")
            return None


    # Proposer le vaccin pour les patients
    def getRdv(patient_id):
        try:
            sql_command = "SELECT patient.nom, patient.prenom, centre.label as centre_label, centre.adresse as centre_adresse, rendezvous.injection as injection, vaccin.label as vaccin_label FROM patient JOIN rendezvous ON patient.id = rendezvous.patient_id JOIN centre ON centre.id = rendezvous.centre_id JOIN vaccin ON vaccin.id = rendezvous.vaccin_id WHERE rendezvous.patient_id=%s ORDER BY rendezvous.injection"
            with connection.cursor() as cursor:
                cursor.execute(sql_command, [patient_id])
                results = cursor.fetchall()

                return results
        except Exception:
            print("ERROR")
            return None


    # Obtenir le nombre des doses d'un type du vaccin
    def getDoseNumberOfVaccin(vaccin_label):
        try:
            sql_command = "SELECT vaccin.doses as doses FROM vaccin WHERE vaccin.label=%s"
            with connection.cursor() as cursor:
                cursor.execute(sql_command, [vaccin_label])
                results = cursor.fetchall()[0][0]

            return results
        except Exception:
            print("ERROR")
            return None


    # Trouver les centres où ils ont au moins une dose de vaccin
    def getActiveDoseFromCenter():
        try:
            sql_command = "SELECT DISTINCT centre.id as centre_id, centre.label as centre_label, centre.adresse as centre_adresse, SUM(stock.quantite) as quantite FROM centre JOIN stock ON centre.id = stock.centre_id GROUP BY centre_id HAVING SUM(stock.quantite) > 0"
            with connection.cursor() as cursor:
                cursor.execute(sql_command)
                activeCenter = cursor.fetchall()

                return activeCenter
        except Exception:
            print("ERROR")
            return None


    # Utilisation: Trouver les centres de vaccination qui ont le vaccine que le patient a été vacciné
    def getCenterByVaccin(vaccin_label):
        try:
            sql_command = "SELECT DISTINCT centre.id as centre_id, centre.label as centre_label, centre.adresse as centre_adresse, SUM(stock.quantite) as quantite FROM centre JOIN stock ON centre.id = stock.centre_id JOIN vaccin ON vaccin.id = stock.vaccin_id WHERE vaccin.label=%s GROUP BY centre_id HAVING SUM(stock.quantite) > 0"
            with connection.cursor() as cursor:
                cursor.execute(sql_command, [vaccin_label])
                activeCenter = cursor.fetchall()

                return activeCenter
        except Exception:
            print("ERROR")
            return None


    # Définir un rendez-vous pour le patient
    def setRdv(centre_id, centre_label, patient_id, injection):
        if len(centre_id) > 0 and len(centre_label) > 0 and len(patient_id) > 0:
            try:
                # 1) Choisir un vaccin dans le centre choisi dont le vaccin de ce type a le nombre des doses le plus grand
                # On l'appelle 'VACCIN_G"
                sql_command = "SELECT MAX(stock.quantite) as quantite FROM stock WHERE stock.centre_id=%s"
                with connection.cursor() as cursor:
                    cursor.execute(sql_command, [centre_id])
                    maxDose = cursor.fetchall()[0][0]

                # 2) On prend les infos du 'VACCIN_G' au centre choisi comme vaccin(id, lour le proposer au patient
                    # 2.1) Si ce patient a déjà un rendez-vous au centre de vaccination, on va trouver le nom du vaccin dans sa première dose
                    # 2.2) Au contraire, on va trouver les centres qui ont le vaccin avec le nombre des doses positif pour ce patient
                    # et on choisi le centre qui a le nombre des doses le plus grand.
                sql_command = "SELECT rendezvous.vaccin_id as vaccin_id FROM rendezvous WHERE rendezvous.patient_id=%s"
                with connection.cursor() as cursor:
                    cursor.execute(sql_command, [patient_id])
                    vaccin_id = cursor.fetchall()

                # **** 2.1) Il y a pas de rendez-vous ****
                vaccinInfo = ''
                if len(vaccin_id) == 0:
                    sql_command = "SELECT vaccin.id as vaccin_id, vaccin.label as vaccin_label, stock.quantite as quantite FROM vaccin JOIN stock ON vaccin.id = stock.vaccin_id WHERE stock.centre_id=%s AND stock.quantite=%s"
                    with connection.cursor() as cursor:
                        cursor.execute(sql_command, [centre_id, maxDose])
                        vaccinInfo = cursor.fetchall()[0]
                        vaccin_id = vaccinInfo[0]
                        print("vaccin_id in stock", vaccin_id)

                # **** 2.2) Au contraire...: ***
                else:
                    vaccin_id = vaccin_id[0][0]

                    sql_command = "SELECT vaccin.id as vaccin_id, vaccin.label as vaccin_label, stock.quantite as quantite FROM vaccin JOIN stock ON vaccin.id = stock.vaccin_id WHERE stock.centre_id=%s AND vaccin.id=%s"
                    with connection.cursor() as cursor:
                        cursor.execute(sql_command, [centre_id, vaccin_id])
                        vaccinInfo = cursor.fetchall()[0]

                # pour savoir le nombre des doses resté d'un vaccin dans un centre
                # s'il y as plus de doses d'un vaccin dans un centre, on va notifier au patient
                # sinon, on va ajouter un rendez-vous pour ce patient et on met à jour le stock
                quantite = int(vaccinInfo[2]) - 1

                # 3) On va ajouter un rendez-vous pour ce e patient est vacciné le vaccin choisi par le système
                # -> le nombre de doses de ce vaccin au centre choisi par le patient est donc le plus grand nombre
                if (quantite >= 0):
                    # sql_command = "INSERT INTO rendezvous values (:centre_id, :patient_id, :injection, :vaccin_id)"
                    sql_command = "INSERT INTO rendezvous values (%s, %s, %s, %s)"
                    with connection.cursor() as cursor:
                        cursor.execute(sql_command, [centre_id, patient_id, injection, vaccin_id])  
                else: 
                    return -1

                # 4) On mis à jour le stock (en decrémentant la quantité des doses de ce 'VACCIN_G'
                sql_command = "UPDATE stock SET stock.quantite=%s WHERE stock.centre_id=%s AND stock.vaccin_id=%s"
                with connection.cursor() as cursor:
                    cursor.execute(sql_command, [quantite, centre_id, vaccin_id])

                results = [centre_label, vaccinInfo[1]]
                return results
            except Exception:
                print("ERROR")
                return None
        else: return None

    # Ajouter vaccins aux centres pour le stock
    def attributeVaccin():
        try:
            results = dict()

            sql_command = "SELECT distinct centre.label as centre_label FROM centre JOIN stock ON centre.id = stock.centre_id"
            with connection.cursor() as cursor:
                cursor.execute(sql_command)
                results['centre'] = cursor.fetchall()

            sql_command = "SELECT distinct vaccin.label as vaccin_label FROM vaccin JOIN stock ON vaccin.id = stock.vaccin_id"
            with connection.cursor() as cursor:
                cursor.execute(sql_command)
                results['vaccin'] = cursor.fetchall()

            return results
        except Exception:
            print("ERROR")
            return None

    class Meta:
        db_table = "rendezvous"

djangoVaccination/rdv/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .models import ModelRdv
import re

# Create your views here.

def rdvReadAll(request):
    results = ModelRdv.getAll()   
    return render(request, "rdv/viewAll.html", context={'results': results})

    
def rdvReadPatient(request):
    if request.method == 'GET':
        path_info = request.META['PATH_INFO']
        query_str = re.search(r'target\=[a-zA-Z0-9]*', path_info).group()
        target_value = re.split(r'target\=|\&', query_str)[1]
        target = f'rdv:{target_value}'

        results = ModelRdv.getPatient()
        return render(request, "rdv/viewPatient.html", context={'results': results, 'target': target})

# Voir le rendez-vous vacciné d'un patient
def rdvPropos(request):
    if request.method == 'GET':
        patientInfo = request.GET['patientInfo']
        patient_id = re.split(":", patientInfo)[0].strip()
        
        results = ModelRdv.getRdv(patient_id)                # il faut vérifier s'elle est nulle ou pas
        activeCenter = ModelRdv.getActiveDoseFromCenter()    # cela pour proposer ce qui n'a pas encore un rendez-vous
        
        numberOfDose = patient_injection = centerByVaccin = ''   # celles pour bien savoir si le patient doit vacciner encore une fois ou pas
        if len(results) > 0:
            numberOfDose =  int(ModelRdv.getDoseNumberOfVaccin(results[0][5]))
            patient_injection = int(results[len(results) - 1][4])
            centerByVaccin = ModelRdv.getCenterByVaccin(results[0][5])


        patientId = re.split(":", patientInfo)[0]
        patientInfo = patientInfo[4:]      
        if len(results) > 0:
            if numberOfDose > patient_injection:  
                activeCenter = centerByVaccin                

        info_dict = {
                        "results": results, "numberOfDose": numberOfDose, "patientInfo": patientInfo, "patient_injection": patient_injection, 
                        "patientId": patientId, "centerByVaccin": centerByVaccin, "activeCenter": activeCenter,
                    }
                    
        return render(request, "rdv/viewRdvPropos.html", context=info_dict)


# Définir un rendez-vous pour le patient
def setRdv(request):
    if request.method == 'GET':
        patient_id = request.GET['patientId']
        centre_id = re.split(":", request.GET['centreInfo'])[0].strip()
        centre_label = re.split(":", request.GET['centreInfo'])[1].strip()
        centre_adresse = re.split(":", request.GET['centreInfo'])[2].strip()
        injection = int(ModelRdv.getInjection(patient_id)) + 1
        print("injection", injection)
        
        results = ModelRdv.setRdv(centre_id, centre_label, patient_id, injection)
        results_dict = { "results": results, "centre_label": centre_label, "centre_adresse": centre_adresse, "injection": injection }

        return render(request, "rdv/viewSetRdv.html", context=results_dict)
   

djangoVaccination/templates/rdv/viewAll.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">
            Liste des rendez-vous ...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}
    
    <h4 style="color: #5a5050; margin-bottom: 24px;">Liste des rendez-vous disponibles: </h4>
    <table class='table table-striped table-bordered table-hover'>
        <thead>
            <tr style='background-color: #AA6C39'>
                <th scope='col'>nom</th>
                <th scope='col'>prénom</th>
                <th scope='col'>centre de vaccination</th>
                <th scope='col'>adresse</th>
                <th scope='col'>injection</th>
                <th scope='col'>nom de vaccin</th>
            </tr>
        </thead>

        <tbody>
            {% for rdv in results %}
                <tr>
                    <td>{{ rdv.0 }}</td>
                    <td>{{ rdv.1 }}</td>
                    <td>{{ rdv.2 }}</td>
                    <td>{{ rdv.3 }}</td>
                    <td>{{ rdv.4 }}</td>
                    <td>{{ rdv.5 }}</td>    
                </tr>   
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}

djangoVaccination/templates/rdv/viewPatient.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">
            Liste des patients en attente ...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    <form role="form" method="GET" action="{% url target %}" style="margin-bottom: 8px;">
        <div class="form-group">
            {% comment %} <input type="hidden" name='action' value={{target}}> {% endcomment %}
            <label for="id">View patient : </label> 
            <select class="form-control" id='patientInfo' name='patientInfo' style="width: 140px">
                {% for patient in results %}
                    <option>{{patient.0}} : {{patient.1}} : {{patient.2}} : {{patient.3}}</option>
                {% endfor %}
            </select>
        </div>
        
        <button class="btn btn-primary" type="submit">Submit form</button>
    </form>
    {% endblock%}

djangoVaccination/templates/rdv/viewRdvInfo.html
<h4 style='color: #5a5050; margin-bottom: 24px;'>{{ patientInfo }} veut prendre un rendez-vous pour vacciner. Ajoutez un nouveau rendez-vous: </h4>   
<form role='form' method="GET" action="{% url 'rdv:setRdv' %}" style="margin-bottom: 8px;">
    <div class='form-group'>
        {% comment %} <input type='hidden' name='action' value='setRdv'> {% endcomment %}
        <input type='hidden' name='patientId' value={{ patientId }}>
        <label for='centreInfo'>Choisir le centre où vous voulez vacciner: </label> 
        <select class='form-control' id='centreInfo' name='centreInfo' style='width: 140px'>      
        {% for center in activeCenter %}
            <option>
                {{ center.0 }} : {{ center.1 }} : {{ center.2 }}
            </option>
        {% endfor %}
        {{ activeCenter }}
        </select>
    </div>
    <button class='btn btn-primary' type='submit'>Submit form</button>
</form>

djangoVaccination/templates/rdv/viewRdvPropos.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax parallax2">
        <div class="titre">
            Proposition vaccinée pour nos patients ...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    <h3>Information de rendez-vous: </h3>
    {% comment %} ******** Proposer un rendez-vous pour le patient d'après son injection... ******** {% endcomment %}
    {% comment %} 1) Si le nombre de doses est égal à l'ịnjection du patient, ce patient n'a pas besoin de vacciner {% endcomment %}
    {% comment %} alors ce patient ne peut pas venir à la page de 'pris d'un rendez-vous' ('viewSetRdv') {% endcomment %}
    {% comment %}  {% endcomment %}
    {% comment %} 2) Si le nombre de doses est supérieur à l'ịnjection du patient, ce patient a besoin de vacciner plus fois {% endcomment %}
    {% comment %} jusqu'à le nombre de doses demandé {% endcomment %}

    {% if results|length > 0 %}
        <h4 style='color: #5a5050; margin-bottom: 24px;'>Vous avez déjà pris un rendez-vous. </h4>
        <table class='table table-striped table-bordered table-hover'>
            <thead>
                <tr style='background-color: #AA6C39'>
                    <th scope='col'>nom</th>
                    <th scope='col'>prénom</th>
                    <th scope='col'>centre de vaccination</th>
                    <th scope='col'>adresse</th>
                    <th scope='col'>injection</th>
                    <th scope='col'>nom de vaccin</th>
                </tr>
            </thead>

            <tbody>
            {% for rdv in results %}
                <tr>
                    <td>{{ rdv.0 }}</td>
                    <td>{{ rdv.1 }}</td>
                    <td>{{ rdv.2 }}</td>
                    <td>{{ rdv.3 }}</td>
                    <td>{{ rdv.4 }}</td>
                    <td>{{ rdv.5 }}</td>    
                </tr>   
            {% endfor %} 
            </tbody>
        </table>

        {% if numberOfDose == patient_injection %}
            <h4 style='color: #5a5050; margin-bottom: 24px;'>Vous avez reçu la dose complète de vaccin . <br>
            Les doses proposées du vaccin {{ results.0.5 }} par le ministère de la Santé sont {{ numberOfDose }} doses.</h4>
                    
            <button class='btn btn-primary' style='margin-bottom:7px;' onclick='history.go(-1)'>Page précédente</button>
                        
        {% elif numberOfDose > patient_injection %}
            {% include 'rdv/viewRdvInfo.html' %}
        {% endif %}
         
    {% else %}
        <h4 style='color: #5a5050; margin-bottom: 24px;'>Vous n'avez aucun rendez-vous avec notre centre de vaccination.</h4>
        {% include 'rdv/viewRdvInfo.html' %}         
    {% endif %}
    {% endblock %}

djangoVaccination/templates/rdv/viewSetRdv.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax">
        <div class="titre">
            Allez prendre un rendez-vous avec notre centre de vaccination ...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}
    
    <form class="navbar-form navbar-right" role="search" method="get" action="router2.php" style="margin-bottom: 14px">
        <input type="hidden" name="action" value="searchVaccin">
        <div class="form-group">
            <input name="searching" type="text" class="form-control" size='44' placeholder="Rechercher vaccin par label...">
        </div>
        <button type="submit" class="btn btn-danger">Rechercher</button>
    </form>

    <table class="table table-striped table-bordered table-hover" style="margin-top: 14px">
        <thead>
            <tr style="background-color: #AA6C39">
                <th scope="col">centre</th>
                <th scope="col">adresse</th>
                <th scope="col">vaccin</th>
                <th scope="col">injection</th>
            </tr>
        </thead>

        <tbody>
        {% if results|length > 0 %} 
            <tr>
                <td>{{ centre_label }}</td>
                <td>{{ centre_adresse }}</td>
                <td>{{ results.1 }}</td>
                <td>{{ injection }}</td>
            </tr> 
        {% endif %}
        </tbody>
    </table>

    {% if results != None %} 
        {% if results|length > 0 %} 
            <h3 style='margin-bottom: 20px;'>Vous avez réussi à prendre un rendez-vous au centre {{ centre_label }}. <br>
                Vous serez vacciné(e) le vaccin {{ results.1 }}.</h3>
        {% else %}
            <h3 style='margin-bottom: 20px; '>Vous avez déjà pris un rendez-vous. Veuillez revenir à la page d'accueil. <br></h3>
        {% endif %}
    {% else %}
        <h3 style='margin-bottom: 20px; '>Le centre {{ centre_label }} n'a aucune vaccin de ve type. Veuillez attendre notre nouvelle nofitication.<br></h3>
    {% endif %}
    
    <a href="{% url 'index' %}" class='btn btn-primary' style='margin-bottom:7px;' >Page accueil</a>
    {% endblock %}