djangoVaccination/djangoVaccination/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('vaccin/', include("vaccin.urls")),
    path('centre/', include("centre.urls")),
    path('patient/', include("patient.urls")),
    path('stock/', include("stock.urls")),
    path('rdv/', include("rdv.urls")),
    path('search/', include("search.urls")),
]

djangoVaccination/rdv/urls.py
from django.urls import path
from rdv import views

app_name = 'rdv'
urlpatterns = [
    path(r'?action=rdvReadPatient&target=rdvPropos', views.rdvReadPatient, name='rdvReadPatient'),
    path(r'?action=rdvPropos', views.rdvPropos, name='rdvPropos'),
    path(r'?action=setRdv', views.setRdv, name='setRdv'),
    path(r'?action=rdvReadAll', views.rdvReadAll, name='rdvReadAll'),
]

djangoVaccination/vaccin/urls.py
from django.urls import path
from vaccin import views

app_name = 'vaccin'
urlpatterns = [
    path(r'', views.vaccinReadAll, name='vaccinReadAll'),
    path(r'?action=vaccinReadLabel&target=vaccinReadOne', views.vaccinReadLabel, name='vaccinReadLabel'),
    path(r'?action=vaccinReadOne', views.vaccinReadOne, name='vaccinReadOne'),
    path(r'?action=vaccinCreate', views.vaccinCreate, name='vaccinCreate'),
    path(r'?action=vaccinCreated', views.vaccinCreated, name='vaccinCreated'),
    path(r'?action=vaccinReadLabel&target=vaccinDeleted', views.vaccinReadLabel, name='vaccinDelete'),
    path(r'?action=vaccinDeleted', views.vaccinDeleted, name="vaccinDeleted"),
    path(r'?action=vaccinModifyDose', views.vaccinModifyDose, name="vaccinModifyDose"),
    path(r'?action=vaccinUpdateDose', views.vaccinUpdateDose, name="vaccinUpdateDose"),
]

djangoVaccination/vaccin/models.py
from django.db import connection
from django.db import models
from django.db.models.fields import CharField

# Create your models here.


class ModelVaccin(models.Model):
    label = models.CharField(max_length=70)
    doses = models.IntegerField()

    @staticmethod
    def getOne(label):
        sql_command = "SELECT * FROM vaccin WHERE label=%s;"
        vaccin_rows = ModelVaccin.objects.raw(sql_command, [label])
        return vaccin_rows

    @staticmethod
    def getAll():
        sql_command = "SELECT * FROM vaccin"
        vaccin_rows = ModelVaccin.objects.raw(sql_command)
        return vaccin_rows

    @staticmethod
    def getAllLabel():
        sql_command = "SELECT label from vaccin"
        with connection.cursor() as cursor:
            cursor.execute(sql_command)
            label_list = cursor.fetchall()


    @staticmethod
    def insert(label, doses):
        sql_idMax = "SELECT MAX(id) FROM vaccin"
        with connection.cursor() as cursor:
            cursor.execute(sql_idMax)
            idMax = int(cursor.fetchone()[0]) + 1

        with connection.cursor() as cursor:
            sql_command = "INSERT INTO vaccin VALUE (%s, %s, %s);"
            cursor.execute(sql_command, [idMax, label, doses])

        # vaccin_inserted = ModelVaccin.objects.raw(sql_command, [idMax, label, doses])
        return idMax

    @staticmethod
    def deleteLabel(vaccin_label):
        sql_command = "DELETE FROM vaccin WHERE label=%s"
        with connection.cursor() as cursor:
            cursor.execute(sql_command, [vaccin_label])
        
        # Update list of vaccins
        sql_command = "SELECT * FROM vaccin"
        with connection.cursor() as cursor:
            cursor.execute(sql_command)
            vaccin_info = cursor.fetchall()
            print(vaccin_info)
            return vaccin_info

    @staticmethod
    def updateDose(vaccin_label, quantite):
        sql_command = "SELECT doses FROM vaccin WHERE label=%s"
        with connection.cursor() as cursor:
            cursor.execute(sql_command, [vaccin_label])
            result = cursor.fetchone()[0]
            doses = int(quantite) + int(result)
            print("doses", doses)

        sql_command = "UPDATE vaccin SET doses=%s WHERE label=%s"
        with connection.cursor() as cursor:
            cursor.execute(sql_command, [doses, vaccin_label])

    class Meta:
        db_table = "vaccin"

djangoVaccination/vaccin/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .models import ModelVaccin
import re

# Create your views here.
def strip_tags(value):
    """Return the given HTML with all tags stripped."""
    # Note: in typical case this loop executes _strip_once once. Loop condition
    # is redundant, but helps to reduce number of executions of _strip_once.
    value = str(value)
    while '<' in value and '>' in value:
        new_value = _strip_once(value)
        if value.count('<') == new_value.count('<'):
            # _strip_once wasn't able to detect more tags.
            break
        value = new_value
    return value

# All vaccines's infos
def vaccinReadAll(request):
    vaccin_info = ModelVaccin.objects.all()
    vaccin_dict = {'vaccin_info': vaccin_info}

    return render(request, 'vaccin/viewAll.html', context=vaccin_dict)

# Selection of 1 type of vaccine
def vaccinReadLabel(request):
    if request.method == 'GET':
        path_info = request.META['PATH_INFO']
        query_str = re.search(r'target\=[a-zA-Z0-9]*', path_info).group()
        target_value = re.split(r'target\=|\&', query_str)[1]
        target = f'vaccin:{target_value}'

        vaccin_info = ModelVaccin.objects.all()
        vaccin_dict = {'vaccin_info': vaccin_info, 'target': target}

        return render(request, 'vaccin/viewLabel.html', context=vaccin_dict)

# Show one vaccine's info from selection view
def vaccinReadOne(request):
    if request.method == 'GET':
        label = request.GET['label']
        vaccin_info = ModelVaccin.getOne(label)
        vaccin_dict = {'vaccin_info': vaccin_info}
        return render(request, 'vaccin/viewAll.html', context=vaccin_dict)

# Creation's vaccine interface
def vaccinCreate(request):
    return render(request, 'vaccin/viewInsert.html', context={})

# Create a new vaccine
@csrf_exempt
def vaccinCreated(request):
    if request.method == 'POST':
        label = request.POST['label'].strip()
        doses = request.POST['doses'].strip()

        condition1 = (not label) or (not doses)
        condition2 = (len(label) > 0) and (len(doses) > 0)

        if (condition1):
            info_dict = {'result': False}
        elif (condition2):
            try:
                # Add new vaccine to database (table 'vaccin')
                id = ModelVaccin.insert(strip_tags(label), strip_tags(doses))
                vaccin_info = ModelVaccin.objects.all()

                info_dict = {'result': True, 'id': id, 'label': label,
                            'doses': doses, 'vaccin_info': vaccin_info}
            except Exception:
                info_dict = {'result': False}

        return render(request, 'vaccin/viewInserted.html', context=info_dict)

# Delete a vaccine from its label
def vaccinDeleted(request):
    if request.method == 'GET':
        label = request.GET['label']
        vaccin_info = ModelVaccin.deleteLabel(label)
        vaccin_dict = {'vaccin_info': vaccin_info, 'label': label}

        return render(request, 'vaccin/viewDeleted.html', context=vaccin_dict)

# Modify the number of dose(s) page
def vaccinModifyDose(request):
    vaccin_info = ModelVaccin.getAll()

    return render(request, 'vaccin/viewModifyDose.html', context={'vaccin_info': vaccin_info})


# Update number of doses 
def vaccinUpdateDose(request):
    if (request.method == 'GET'):
        vaccin_label = request.GET['label']
        quantite = request.GET['quantite']

        ModelVaccin.updateDose(vaccin_label, quantite)
        vaccin_info = ModelVaccin.getAll()
        vaccin_dict = {'vaccin_info': vaccin_info, 'vaccin_label': vaccin_label}

        return render(request, 'vaccin/viewUpdateDose.html', context=vaccin_dict)

djangoVaccination/templates/vaccin/viewAll.html
{% extends "fragment/framePage.html" %}
    {% block body_block %}
    <form class="navbar-form navbar-right" role="search" method="get" action="router2.php" style="margin-bottom: 14px">
        <!-- Ensure the security of the form submitting -->
        {% csrf_token %}

        <input type="hidden" name="action" value="searchVaccin">
        <div class="form-group">
            <input name="searching" type="text" class="form-control" size='44' placeholder="Rechercher par label...">
        </div>
        <button type="submit" class="btn btn-danger">Rechercher</button>
    </form>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #AA6C39">
                <th scope="col">id</th>
                <th scope="col">label</th>
                <th scope="col">doses</th>
            </tr>
        </thead>

        <tbody>
            {% for vaccin in vaccin_info %}
                <tr>
                    <td>{{vaccin.id}}</td>
                    <td>{{vaccin.label}}</td>
                    <td>{{vaccin.doses}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}

djangoVaccination/templates/vaccin/viewDeleted.html
{% extends 'fragment/framePage.html' %}
    {% block body_block %}
    <div style="margin-bottom: 20px">
        <h3>Le vaccin {{ label }} a bien été supprimé.
            <br> Voici la nouvelle liste des vaccins : <br>
        </h3>
    </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #AA6C39">
                <th scope="col">id</th>
                <th scope="col">label</th>
                <th scope="col">doses</th>
            </tr>
        </thead>
        
        <tbody>
        {% comment %} La liste des vaccins est dans une variable $results {% endcomment %}
        {% for vaccin in vaccin_info %}
            <tr>
                <td>{{ vaccin.0 }}</td>
                <td>{{ vaccin.1 }}</td>
                <td>{{ vaccin.2 }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endblock %}

djangoVaccination/templates/vaccin/viewInsert.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax">
        <div class="titre"><br>Ajoutez un vaccin à notre centre de vaccination!</div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    <!-- Ensure the security of the form submitting -->
    {% csrf_token %}
    <form role="form" method='POST' action="{% url 'vaccin:vaccinCreated' %}" style="margin-bottom: 8px">
        <div class="form-group">
            {% comment %} <input type="hidden" name='action' value='vaccinCreated'>         {% endcomment %}
            <label for="id">label : </label><input type="text" name='label' size='75' value=''>                           
            <label for="id">doses : </label><input type="text" name='doses' value='2'>            
        </div>
        <button class="btn btn-primary" type="submit">Go</button>
    </form>
    {% endblock %}

djangoVaccination/templates/vaccin/viewInserted.html
{% extends "fragment/framePage.html" %} 
{% block body_block %} 
    {% csrf_token %}    

    {% if result %}
    <h3>Le nouveau vaccin a été ajouté</h3>
    <ul>
        <li>id = {{ id }}</li>
        <li>label = {{ label }}</li>
        <li>doses = {{ doses }}</li>
    </ul>

    <h3>Voici la nouvelle liste des vaccins:</h3>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #aa6c39">
                <th scope="col">id</th>
                <th scope="col">label</th>
                <th scope="col">doses</th>
            </tr>
        </thead>
        <tbody>
            {% for vaccin in vaccin_info %}
            <tr>
                <td>{{ vaccin.id }}</td>
                <td>{{ vaccin.label }}</td>
                <td>{{ vaccin.doses }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
        <h3>Problème d'insertion du Vaccin.</h3>
        <h3 style="color: red" ;>
        Veuillez vérifier toutes les infos du vaccin dans le formulaire ont été bien
        renseignées ou le nom du vaccin est dupliqué.
        </h3>
    {% endif %}

    <button class="btn btn-primary" style="margin-bottom: 7px" onclick="history.go(-1)" style="margin-bottom: 8px">
    Page précédente
    </button>
{% endblock %}

djangoVaccination/templates/vaccin/viewLabel.html
{% extends "fragment/framePage.html" %}
    {% block background_block %}
    <div class="parallax">
        <div class="titre">Découvrez nos vaccins...</div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}
    
    <form role="form" method='GET' action="{% url target %}" style="margin-bottom: 8px">
        <div class="form-group">
            {% comment %} <input type="hidden" name='action' value={{target}}> {% endcomment %}
            <label for="label">Choisir un vaccin : </label> 
            <select class="form-control" id='label' name='label' style="width: 100px">
                {% for vaccin in vaccin_info %}
                    <option>{{ vaccin.label }}</option>
                {% endfor %}
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Submit form</button>
    </form>
    {% endblock %}

djangoVaccination/templates/vaccin/viewModifyDose.html
{% extends "fragment/framePage.html" %} 
    {% block background_block %}
    <div class="parallax">
        <div class="titre">
            Modifiez la quantité d'une dose en ajoutant des nouvelles ...
        </div>
    </div>
    {% endblock %}

    {% block body_block %}
    {% block jumbotron_block %}
        {% include "fragment/frameJumbotron.html" %}
    {% endblock %}

    <form class="navbar-form navbar-right" role="search" method="get" action="router2.php" style="margin-bottom: 14px">
        <input type="hidden" name="action" value="searchVaccin" />
        <div class="form-group">
            <input name="searching" type="text" class="form-control" size="44" placeholder="Rechercher par label..."/>
        </div>
        <button type="submit" class="btn btn-danger">Rechercher</button>
    </form>

    <br /><br />

    <form role="form" method="GET" action="{% url 'vaccin:vaccinUpdateDose' %}" style="margin-top: 8px; margin-bottom: 8px">
        <div class="form-group">
            {% comment %} <input type="hidden" name="action" value="vaccinUpdateDose" /> {% endcomment %}
            <label for="label">vaccin_label : </label>
            <select class="form-control" id="label" name="label" style="width: 100px">
                {% for vaccin in vaccin_info %}
                    <option>{{ vaccin.label }}</option>
                {% endfor %}
            </select>

            <label for="quantite" style="margin-top: 8px">Nombre des doses ajoutées :</label>
            <input type="number" id="quantite" name="quantite" value="1" />
        </div>
        <button class="btn btn-primary" type="submit">Ajouter</button>
    </form>

    {% endblock %}

djangoVaccination/templates/vaccin/viewUpdateDose.html
{% extends "fragment/framePage.html" %}
    {% block body_block %}
        {% block jumbotron_block %}
            {% include "fragment/frameJumbotron.html" %}
        {% endblock %}

        <form class="navbar-form navbar-right" role="search" method="get" action="router2.php" style="margin-bottom: 14px">
            <input type="hidden" name="action" value="searchVaccin">
            <div class="form-group">
                <input name="searching" type="text" class="form-control" size='44' placeholder="Rechercher par label...">
            </div>
            <button type="submit" class="btn btn-danger">Rechercher</button>
        </form>
        
        <br><br>
        
        <div style="margin-bottom: 20px">
            <h3>Le vaccin {{ vaccin_label }} a bien été modifié.
                <br> Voici la nouvelle liste des vaccins : <br>
            </h3>
        </div>
        
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr style="background-color: #AA6C39">
                    <th scope="col">id</th>
                    <th scope="col">label</th>
                    <th scope="col">doses</th>
                </tr>
            </thead>

            <tbody>
                {% for vaccin in vaccin_info %}
                <tr>
                    <td>{{ vaccin.id }}</td>
                    <td>{{ vaccin.label }}</td>
                    <td>{{ vaccin.doses }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-primary" style="margin-bottom:7px;" onclick="history.go(-1)" style="margin-bottom: 8px">Page précédente</button>
    {% endblock %}