djangoVaccination/centre/urls.py
from django.urls import path
from centre import views

app_name = 'centre'
urlpatterns = [
    path(r'', views.centreReadAll, name='centreReadAll'),
    path(r'?action=centreReadLabel&target=centreReadOne', views.centreReadLabel, name='centreReadLabel'),
    path(r'?action=centreReadOne', views.centreReadOne, name='centreReadOne'),
    path(r'?action=centreCreate', views.centreCreate, name='centreCreate'),
    path(r'?action=centreCreated', views.centreCreated, name='centreCreated'),
    path(r'?action=centreReadLabel&target=centreDeleted', views.centreReadLabel, name='centreDelete'),
    path(r'?action=centreDeleted', views.centreDeleted, name='centreDeleted'),
]

djangoVaccination/djangoVaccination/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('vaccin/', include("vaccin.urls")),
    path('centre/', include("centre.urls")),
    path('patient/', include("patient.urls")),
    path('stock/', include("stock.urls")),
    path('rdv/', include("rdv.urls")),
    path('search/', include("search.urls")),
]

djangoVaccination/patient/urls.py
from django.urls import path
from patient import views

app_name = 'patient'
urlpatterns = [
    path(r'', views.patientReadAll, name='patientReadAll'),
    path(r'?action=patientReadId&target=patientReadOne', views.patientReadId, name='patientReadId'),
    path(r'?action=patientReadOne', views.patientReadOne, name='patientReadOne'),
    path(r'?action=patientCreate', views.patientCreate, name='patientCreate'),
    path(r'?action=patientCreated', views.patientCreated, name='patientCreated'),
    path(r'?action=patientReadDistinct', views.patientReadDistinct, name='patientReadDistinct'),
    path(r'?action=quantityByAdresse', views.quantityByAdresse, name='quantityByAdresse'),    
    path(r'?action=patientReadId&target=patientDeleted', views.patientReadId, name='patientDelete'),
    path(r'?action=patientDeleted', views.patientDeleted, name='patientDeleted'),
]

djangoVaccination/rdv/urls.py
from django.urls import path
from rdv import views

app_name = 'rdv'
urlpatterns = [
    path(r'?action=rdvReadPatient&target=rdvPropos', views.rdvReadPatient, name='rdvReadPatient'),
    path(r'?action=rdvPropos', views.rdvPropos, name='rdvPropos'),
    path(r'?action=setRdv', views.setRdv, name='setRdv'),
    path(r'?action=rdvReadAll', views.rdvReadAll, name='rdvReadAll'),
]

djangoVaccination/stock/urls.py
from django.urls import path
from stock import views

app_name = 'stock'
urlpatterns = [
    path(r'?action=stockReadDosesByVaccinByCenter', views.stockReadDosesByVaccinByCenter, name='stockReadDosesByVaccinByCenter'),
    path(r'?action=stockReadDosesByCenter', views.stockReadDosesByCenter, name='stockReadDosesByCenter'),
    path(r'?action=stockAdd&target=stockAdded', views.stockAdd, name='stockAdd'),
    path(r'?action=stockAdded', views.stockAdded, name='stockAdded'),
    path(r'?action=stockAdd&target=stockDeleted', views.stockAdd, name='stockDelete'),
    path(r'?action=stockDeleted', views.stockDeleted, name='stockDeleted'),
]

djangoVaccination/vaccin/urls.py
from django.urls import path
from vaccin import views

app_name = 'vaccin'
urlpatterns = [
    path(r'', views.vaccinReadAll, name='vaccinReadAll'),
    path(r'?action=vaccinReadLabel&target=vaccinReadOne', views.vaccinReadLabel, name='vaccinReadLabel'),
    path(r'?action=vaccinReadOne', views.vaccinReadOne, name='vaccinReadOne'),
    path(r'?action=vaccinCreate', views.vaccinCreate, name='vaccinCreate'),
    path(r'?action=vaccinCreated', views.vaccinCreated, name='vaccinCreated'),
    path(r'?action=vaccinReadLabel&target=vaccinDeleted', views.vaccinReadLabel, name='vaccinDelete'),
    path(r'?action=vaccinDeleted', views.vaccinDeleted, name="vaccinDeleted"),
    path(r'?action=vaccinModifyDose', views.vaccinModifyDose, name="vaccinModifyDose"),
    path(r'?action=vaccinUpdateDose', views.vaccinUpdateDose, name="vaccinUpdateDose"),
]

djangoVaccination/templates/fragment/frameJumbotron.html
<!-- Jumbotron -->
<div class="jumbotron" style="font-family: Verdana, Geneva, sans-serif ">
    <h1 style="color: white">Vaccination Covid 2021 </h1>
    <p style="color: white">Quoi qu'il en coûte ....</p>
</div>

djangoVaccination/templates/fragment/framePage.html
<!DOCTYPE html>
{% load static %}
<html lang="en"
  <head>
    <title>Vaccination contre le COVID-19</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static "images/logo_vaccin.png" %}"
    type="image/icon_type" /> <link href="{% static "css/bootstrap.css" %}"
    rel="stylesheet" /> <link href="{% static "css/perso_css.css" %}"
    rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head

  <body>
    {% block background_block %}
    {% comment %} For background in the heading of the page {% endcomment %}
    {% endblock %}

    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                <div class="bouton-menu" onclick="ouvrirMenu(this)">
                    <div class="containerBarre">
                    <div class="barre1"></div>
                    <div class="barre2"></div>
                    <div class="barre3"></div>
                    </div>
                </div>
                <a class="navbar-brand" href="{% url 'index' %}"
                    >HK & 3T</a
                >
                </div>

                <div class="menu ferme">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                    <a href="#" onclick="ouvrirSousMenu(this)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Gestion des vaccins <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'vaccin:vaccinReadAll' %}">Liste des vaccins</a></li>
                        <li><a href="{% url 'vaccin:vaccinReadLabel' %}">Sélection d'un vaccin par son label</a></li>
                        <li><a href="{% url 'vaccin:vaccinCreate' %}">Ajout d'un vaccin</a></li>
                        <li><a href="{% url 'vaccin:vaccinDelete' %}">Suppression d'un vaccin</a></li>
                        <li><a href="{% url 'vaccin:vaccinModifyDose' %}">Mise à jour d'un vaccin</a></li>
                    </ul>
                    </li>

                    <li class="dropdown">
                    <a href="#" onclick="ouvrirSousMenu(this)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                        >Gestion des centres <span class="caret"></span
                    ></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'centre:centreReadAll' %}">Liste des centres</a></li>
                        <li><a href="{% url 'centre:centreReadLabel' %}">Sélection d'un centre</a></li>
                        <li><a href="{% url 'centre:centreCreate' %}">Ajout d'un centre</a></li>
                        <li><a href="{% url 'centre:centreDelete' %}">Suppression d'un centre</a></li>
                    </ul>
                    </li>

                    <li class="dropdown">
                    <a href="#"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                        >Gestion des patients <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'patient:patientReadAll' %}">Liste des patients</a></li>
                        <li><a href="{% url 'patient:patientReadId' %}"=>Affichage d'un patient par son id</a></li>
                        <li><a href="{% url 'patient:patientCreate' %}">Ajout d'un patient</a></li>
                        <li><a href="{% url 'patient:patientReadDistinct' %}">Liste sans doublon des addresses de patients</a></li>
                        <li><a href="{% url 'patient:quantityByAdresse' %}">Nombre de patients par son addresse</a></li>
                        <li><a href="{% url 'patient:patientDelete' %}">Suppression d'un patient</a></li>
                    </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                        >Gestion des stocks <span class="caret"></span>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'stock:stockReadDosesByVaccinByCenter' %}">Liste des centres avec le nombre de doses de chaque vaccin</a></li>
                        <li><a href="{% url 'stock:stockReadDosesByCenter' %}">Nombre global de doses des centres</a></li>
                        <li><a href="{% url 'stock:stockAdd' %}">Attribution de vaccins pour un centre</a></li>
                        <li><a href="{% url 'stock:stockDelete' %}">Suppression d'un stock</a></li>
                    </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                        >Gestion des rendez-vous<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'rdv:rdvReadPatient' %}">Dossier de vaccination d'un patient</a></li>
                        <li><a href="{% url 'rdv:rdvReadAll' %}">Liste des rendez-vous</a></li>
                    </ul>
                    </li>
                </ul>
                </div>
            </div>
        </nav>

        {% block body_block %}
            {% block jumbotron_block %}
            {% comment %} Jumbotron file {% endcomment %}
            {% endblock %}
        {% endblock %}
    </div>   

    <div class="signature">
      <h4>Huu Khai NGUYEN - Thanh Tri TRAN</h4>
    </div>

    <script type="text/javascript" src="{% static "js/changeBg.js" %}"></script>
    <script type="text/javascript" src="{% static "js/menu.js" %}"></script>
  </body>
</html>